/**
 * Sinh mã giảm giá (giftcode) duy nhất theo cấu hình — dùng cho vòng quay trúng voucher.
 */
import prisma from '../db';

function randomCode(prefix = ''): string {
  const chars = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
  let s = '';
  for (let i = 0; i < 8; i++) s += chars[Math.floor(Math.random() * chars.length)];
  return `${(prefix || '').toUpperCase()}${s}`;
}

export interface GenGiftOpts {
  discountType: 'percent' | 'amount';
  discountValue: number;
  minOrder?: number;
  maxDiscount?: number | null;
  expiryDays?: number | null;
  prefix?: string;
  description?: string;
  perUserLimit?: number;
}

/** Tạo 1 giftcode dùng-một-lần, gắn cờ autoGenerated. Trả về code. */
export async function generateUniqueGiftCode(opts: GenGiftOpts): Promise<string> {
  let code = randomCode(opts.prefix);
  for (let attempt = 0; attempt < 6; attempt++) {
    // eslint-disable-next-line no-await-in-loop
    const exists = await prisma.giftCode.findUnique({ where: { code } });
    if (!exists) break;
    code = randomCode(opts.prefix);
  }
  const expiresAt = opts.expiryDays && opts.expiryDays > 0
    ? new Date(Date.now() + opts.expiryDays * 86400000)
    : null;
  await prisma.giftCode.create({
    data: {
      code,
      discountType: opts.discountType,
      discountValue: opts.discountValue,
      minOrder: opts.minOrder || 0,
      maxDiscount: opts.maxDiscount ?? null,
      usageLimit: 1,
      perUserLimit: opts.perUserLimit || 1,
      expiresAt,
      isActive: true,
      isPublic: false,
      autoGenerated: true,
      description: opts.description || 'Mã trúng từ vòng quay may mắn',
    },
  });
  return code;
}
